version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi # container name given, so that client can connect using container name instead of localhost
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"  #overriding the connection string which is appsettings,database is local there,we change it shoppingdb
    depends_on: # api is dependent on database,container mongo db is created first before api container is created
      - shopping.db
    ports:
      - "8000:80"

  shopping.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: # api is dependent on database and api,container mongo db is created first before api container is created
      - shopping.db
      - shopping.api
    ports:
      - "8001:80"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db